#! /usr/bin/env bash

function part1() {
   local inputPath="${1:-input.txt}"

   paste \
      <(firstColumn "$inputPath" | sort) \
      <(secondColumn "$inputPath" | sort) \
   | awk '
      function abs(x) { return x < 0 ? x * -1 : x }
      { print abs($1 - $2) }
   ' \
   | sumList
}

function part2() {
   local inputPath="${1:-input.txt}"

   join \
      <(firstColumn "$inputPath" | sort) \
      <(secondColumn "$inputPath" | sort | uniq -c | awk '{ print $2, $1}') \
   | awk '{ print $1 * $2 }' \
   | sumList
}

function firstColumn() {
  cut -d' ' -f1 "$@"
}

function secondColumn() {
  cut -d' ' -f4 "$@"
}

function sumList() {
   awk '{ total += $1 } END { print total }'
}
